
r = [{'dataCode': 'rps',
  'description': 'Revenue per share',
  'name': 'Revenue Per Share',
  'statementType': 'overview',
  'units': '$'},
 {'dataCode': 'roa',
  'description': 'Net Income/Total Assets',
  'name': 'Return on Assets ROA',
  'statementType': 'overview',
  'units': '%'},
 {'dataCode': 'assetTurnover',
  'description': 'Revenue over assets',
  'name': 'Asset Turnover',
  'statementType': 'overview',
  'units': None},
 {'dataCode': 'bookVal',
  'description': 'Book value of the share, assets - liabilities',
  'name': 'Book Value',
  'statementType': 'overview',
  'units': '$'},
 {'dataCode': 'bvps',
  'description': 'Book Value per each share',
  'name': 'Book Value Per Share',
  'statementType': 'overview',
  'units': '$'},
 {'dataCode': 'revenue',
  'description': 'Revenue',
  'name': 'Revenue',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'epsDil',
  'description': 'EPS for diluted shares',
  'name': 'Earnings Per Share Diluted',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'netinc',
  'description': 'Net income',
  'name': 'Net Income',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'profitMargin',
  'description': 'This field is marked for DEPRECATION. Please use grossMargin instead. Profit Margin is calculated by the (Revenue - COGS)/Revenue',
  'name': 'Profit Margin',
  'statementType': 'overview',
  'units': '%'},
 {'dataCode': 'revenueQoQ',
  'description': 'Revenue Quarter-over-Quarter Growth rate',
  'name': 'Revenue QoQ Growth',
  'statementType': 'overview',
  'units': '%'},
 {'dataCode': 'debtEquity',
  'description': 'Debt/Equity ratio',
  'name': 'Debt to Equity Ratio',
  'statementType': 'overview',
  'units': ''},
 {'dataCode': 'grossMargin',
  'description': 'The margin of good sold, basically how much of the money the company keeps after selling their goods and services. (Rev.-Cost of Rev.)/Rev.',
  'name': 'Gross Margin',
  'statementType': 'overview',
  'units': '%'},
 {'dataCode': 'roe',
  'description': "Return on Shareholder's equity; ROE=Net Income/Shareholder's Equity",
  'name': 'Return on Equity ROE',
  'statementType': 'overview',
  'units': '%'},
 {'dataCode': 'currentRatio',
  'description': 'Ability for a company to pay off its short-term liabilities, Current Assets/Current Liabilities',
  'name': 'Current Ratio',
  'statementType': 'overview',
  'units': ''},
 {'dataCode': 'fxRate',
  'description': 'The exchange rate used for the conversion of foreign currency to USD for non-US companies that do not report in USD.',
  'name': 'FX Rate',
  'statementType': 'overview',
  'units': None},
 {'dataCode': 'sharesBasic',
  'description': 'Outstanding shares',
  'name': 'Shares Outstanding',
  'statementType': 'balanceSheet',
  'units': ''},
 {'dataCode': 'piotroskiFScore',
  'description': "0-9 point scale to determine strength of company's financial position",
  'name': 'Piotroski F-Score',
  'statementType': 'overview',
  'units': None},
 {'dataCode': 'longTermDebtEquity',
  'description': 'Long term debt to equity',
  'name': 'Long-term Debt to Equity',
  'statementType': 'overview',
  'units': None},
 {'dataCode': 'opMargin',
  'description': 'Operating margin, or how much money a company makes on each dollar of revenue. In other words Operating Income/Revenue',
  'name': 'Operating Margin',
  'statementType': 'overview',
  'units': '%'},
 {'dataCode': 'epsQoQ',
  'description': 'Earnings Per Share Quarter-over-Quarter Growth rate',
  'name': 'Earnings Per Share QoQ Growth',
  'statementType': 'overview',
  'units': '%'},
 {'dataCode': 'shareswaDil',
  'description': 'Used to calculated diluted EPS. Considers all outstanding common stock plus all instruments that can be converted into shares (like stock options) ',
  'name': 'Weighted Average Shares Diluted',
  'statementType': 'incomeStatement',
  'units': ''},
 {'dataCode': 'eps',
  'description': 'Earnings per basic share (not diluted)',
  'name': 'Earnings Per Share',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'ppeq',
  'description': 'A component of assets representing the total amount of marketable and non-marketable securties, loans receivable and other invested assets.',
  'name': 'Property, Plant & Equipment',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'ebitda',
  'description': 'EBITDA is a non-GAAP accounting metric that is widely used when assessing the performance of companies, calculated by adding Depreciation/Amortization back to Earnings before interest and taxes',
  'name': 'EBITDA',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'freeCashFlow',
  'description': 'Operating Cash Flow - Capex, How much cash is left over after reinvesting it in the business. Used as a measure to evaluate financial performance of a company',
  'name': 'Free Cash Flow',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'issrepayDebt',
  'description': 'Representing the net cash inflow (outflow) from issuance (repayment) of debt securities.',
  'name': 'Issuance or Repayment of Debt Securities',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'capex',
  'description': 'Money uses to upgrade or acquire property or materials to maintain and increase size',
  'name': 'Capital Expenditure',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'rnd',
  'description': 'The aggregate costs incurred in a planned search or critical investigation aimed at discovery of new knowledge with the hope that such knowledge will be useful in developing a new product or service.',
  'name': 'Research & Development',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'sga',
  'description': "The aggregate total costs related to selling a firm's product and services, as well as all other general and administrative expenses. Direct selling expenses (for example, credit, warranty, and advertising) are expenses that can be directly linked to the sale of specific products. Indirect selling expenses are expenses that cannot be directly linked to the sale of specific products, for example telephone expenses, Internet, and postal charges. General and administrative expenses include salaries",
  'name': 'Selling, General & Administrative',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'investmentsCurrent',
  'description': 'The current portion of Investments, reported if the company operates a classified balance sheet that segments current and non-current assets.',
  'name': 'Current Investments',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'payDiv',
  'description': 'Representing dividends and dividend equivalents paid on common stock and restricted stock units.',
  'name': 'Payment of Dividends & Other Cash Distributions',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'peRatio',
  'description': 'P/E Ratio',
  'name': 'Price to Earnings Ratio',
  'statementType': 'overview',
  'units': ''},
 {'dataCode': 'investmentsAcqDisposals',
  'description': 'A component of cash flow from financing, representing the net cash inflow (outflow) associated with the acquisition & disposal of investments, including marketable securities and loan originations.',
  'name': 'Investment Acquisitions & Disposals',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'taxLiabilities',
  'description': 'A component of liabilities representing outstanding tax liabilities.',
  'name': 'Tax Liabilities',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'ncff',
  'description': 'Net Cash flow from financing activities like issuing stock or debt minus dividends or acquiring debt',
  'name': 'Net Cash Flow from Financing',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'opinc',
  'description': 'Operating income is a measure of financial performance before the deduction of interest expense, tax expenses and other Non-Operating items. It is calculated as gross profit minus operating expenses',
  'name': 'Operating Income',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'nonControllingInterests',
  'description': 'The portion of income which is attributable to non-controlling interest shareholders, subtracted from consolidated income in order to obtain net income',
  'name': 'Net Income to Non-Controlling Interests',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'assetsNonCurrent',
  'description': 'Assets that cannot be easily converted into cash and where the value of the item will be realized in a year',
  'name': 'Other Assets',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'taxAssets',
  'description': 'A component of assets representing tax assets and receivables.',
  'name': 'Tax Assets',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'issrepayEquity',
  'description': 'Representing the net cash inflow (outflow) from issuance (repayment) of equity.',
  'name': 'Issuance or Repayment of Equity',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'ncfx',
  'description': 'Cash flow from exchange rate changes',
  'name': 'Effect of Exchange Rate Changes on Cash',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'ncfo',
  'description': "Cash flow generating from a company's operations",
  'name': 'Net Cash Flow from Operations',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'grossProfit',
  'description': 'Aggregate revenue [REVENUE] less cost of revenue [COR] directly attributable to the revenue generation activity.',
  'name': 'Gross Profit',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'debtCurrent',
  'description': 'Current debt - debt due within a year',
  'name': 'Current Debt',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'retainedEarnings',
  'description': "A component of Shareholder's Equity representing the cumulative amount of the entities undistributed earnings or deficit. May only be reported annually by certain companies, rather than quarterly.",
  'name': 'Accumulated Retained Earnings or Deficit',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'liabilitiesNonCurrent',
  'description': 'Long-term liabilities (like debt) that are not due within a year',
  'name': 'Other Liabilities',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'sbcomp',
  'description': "A component of cash flow from operating activities, representing the total amount of noncash, equity-based employee remuneration. This may include the value of stock or unit options, amortization of restricted stock or units, and adjustment for officers' compensation. As noncash, this element is an add back when calculating net cash generated by operating activities using the indirect method.",
  'name': 'Shared-based Compensation',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'businessAcqDisposals',
  'description': 'A component of cash flow from investing, representing the net cash inflow (outflow) associated with the acquisition & disposal of businesses, joint-ventures, affiliates, and other named investments.',
  'name': 'Business Acquisitions & Disposals',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'liabilitiesCurrent',
  'description': 'Debt or liabilities that are due within a year',
  'name': 'Current Liabilities',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'acctRec',
  'description': 'Amount company will receive based on work already completed and delivered',
  'name': 'Accounts Receivable',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'cashAndEq',
  'description': 'Cash or assets that can be converted to cash immediately',
  'name': 'Cash and Equivalents',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'accoci',
  'description': "Unrealized gains and losses - such as items that have changed in value but haven't been bought or sold yet",
  'name': 'Accumulated Other Comprehensive Income',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'depamor',
  'description': 'Depreciation, Amortization, and Accretion',
  'name': 'Depreciation, Amortization & Accretion',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'assetsCurrent',
  'description': 'Assets that can easily be converted to cash and can be used to fund day-to-day operations',
  'name': 'Current Assets',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'shareswa',
  'description': 'Weighted average shares (undiluted)',
  'name': 'Weighted Average Shares',
  'statementType': 'incomeStatement',
  'units': ''},
 {'dataCode': 'investments',
  'description': 'A component of assets representing the total amount of marketable and non-marketable securties, loans receivable and other invested assets.',
  'name': 'Investments',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'prefDVDs',
  'description': "Impact of dividend on company's preferred shares",
  'name': 'Preferred Dividends Income Statement Impact',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'intangibles',
  'description': 'Goodwill and Intangible Assets',
  'name': 'Intangible Assets',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'opex',
  'description': 'Operating expenses represents the total expenditure on SG&A, R&D and other operating expense items, it excludes cost of revenue.',
  'name': 'Operating Expenses',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'inventory',
  'description': 'A component of Total Assets representing the amount after valuation and reserves of inventory expected to be sold, or consumed within one year or operating cycle, if longer.',
  'name': 'Inventory',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'deposits',
  'description': 'Deposit liabilities, both domestic and international including deposits such as savings deposts',
  'name': 'Deposits',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'ebt',
  'description': 'Revenue - Expenses and excluding tax',
  'name': 'Earnings before tax',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'netMargin',
  'description': 'Net Profit Margin, or the Net Income as a proportion of Revenue. In other words, Net Income/Revenue',
  'name': 'Net Margin',
  'statementType': 'overview',
  'units': '%'},
 {'dataCode': 'investmentsNonCurrent',
  'description': 'The non-current portion of investments, reported if the company operates a classified balance sheet that segments current and non-current assets.',
  'name': 'Non-Current Investments',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'totalAssets',
  'description': 'Total assets',
  'name': 'Total Assets',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'deferredRev',
  'description': 'Revenue that was received, but not yet paid out  including sales, license fees, and royalties, but excluding interest income.',
  'name': 'Deferred Revenue',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'taxExp',
  'description': 'Tax expenses',
  'name': 'Tax Expense',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'debt',
  'description': 'Debt',
  'name': 'Total Debt',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'costRev',
  'description': 'The aggregate cost of goods produced and sold and services rendered during the reporting period.',
  'name': 'Cost of Revenue',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'acctPay',
  'description': 'Short-term debt the company must pay off within a year',
  'name': 'Accounts Payable',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'ncf',
  'description': 'Net Cash flow - Total cash minux liabilities',
  'name': 'Net Cash Flow to Change in Cash & Cash Equivalents',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'netIncDiscOps',
  'description': 'Net income from discontinued operations',
  'name': 'Net Income from Discontinued Operations',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'totalLiabilities',
  'description': 'Total Liabilities',
  'name': 'Total Liabilities',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'ncfi',
  'description': 'Cash flow from investments made by the company',
  'name': 'Net Cash Flow from Investing',
  'statementType': 'cashFlow',
  'units': '$'},
 {'dataCode': 'debtNonCurrent',
  'description': 'Longer-term debt, typically greater than a year',
  'name': 'Non-Current Debt',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'ebit',
  'description': 'Earning Before Interest & Taxes (EBIT)',
  'name': 'Earning Before Interest & Taxes EBIT',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'netIncComStock',
  'description': 'Net Income applied to common share holders. Used in calculating EPS (earnings per share).',
  'name': 'Net Income Common Stock',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'intexp',
  'description': 'Interest expense',
  'name': 'Interest Expense',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'consolidatedIncome',
  'description': 'The portion of profit or loss for the period, net of income taxes, which is attributable to the consolidated entity.',
  'name': 'Consolidated Income',
  'statementType': 'incomeStatement',
  'units': '$'},
 {'dataCode': 'equity',
  'description': 'Shareholders Equity',
  'name': 'Shareholders Equity',
  'statementType': 'balanceSheet',
  'units': '$'},
 {'dataCode': 'marketCap',
  'description': 'Size of the company (shares outstanding * share price)',
  'name': 'Market Capitalization',
  'statementType': 'overview',
  'units': '$'},
 {'dataCode': 'enterpriseVal',
  'description': "An alternative to marketcap that's the theoretical takeover price of a company (marketcap + debt - cash and cash equivalents)",
  'name': 'Enterprise Value',
  'statementType': 'overview',
  'units': '$'},
 {'dataCode': 'pbRatio',
  'description': 'Price/Book value per share ratio',
  'name': 'Price to Book Ratio',
  'statementType': 'overview',
  'units': None},
 {'dataCode': 'trailingPEG1Y',
  'description': 'PEG ratio using the trailing 1 year EPS growth rate in the denominator',
  'name': 'PEG Ratio',
  'statementType': 'overview',
  'units': None},
 {'dataCode': 'shareFactor',
  'description': 'Share factor is a multiplicant in the calculation of [MARKETCAP]. For the overwhelming majority of companies its value will be 1. For American Depository Receipts (ADRs) and companies which have different earnings share for different share classes (eg Berkshire Hathaway - BRKB).',
  'name': 'Share Factor',
  'statementType': 'overview',
  'units': None}]

